### ISSUE TITLE
feat: 포토 UI 구현 

### ISSUE THREAD

**Issue by GEONU-MOON** [NongMoong-Lab/doori-world#18]
## New Features

1. 포토 UI 구현

### Todos

- [x] 게시판 UI 구현하기
- [x] 작성폼 UI 구현하기
- [x] CSS 파일 중첩 로드 에러 해결

### References
- Related Issue: #11
